//This one will contain all of the changes just for Z-A
var MOVES_ZA = {};
['(No Move)',
    'Fire Punch', 'Ice Punch', 'Thunder Punch', 'Swords Dance', 'Gust', 'Wing Attack', 'Whirlwind', 'Fly', 'Vine Whip', 'Headbutt', 'Tackle', 'Body Slam',
    'Take Down', 'Double-Edge', 'Tail Whip', 'Poison Sting', 'Pin Missile', 'Leer', 'Bite', 'Growl', 'Roar', 'Supersonic', 'Ember', 'Flamethrower', 'Mist',
    'Water Gun', 'Hydro Pump', 'Surf', 'Ice Beam', 'Blizzard', 'Psybeam', 'Bubble Beam', 'Hyper Beam', 'Peck', 'Absorb', 'Leech Seed', 'Growth', 'Razor Leaf',
    'Solar Beam', 'Poison Powder', 'Stun Spore', 'Sleep Powder', 'String Shot', 'Fire Spin', 'Thunder Shock', 'Thunderbolt', 'Thunder Wave', 'Thunder',
    'Rock Throw', 'Earthquake', 'Dig', 'Toxic', 'Confusion', 'Psychic', 'Hypnosis', 'Agility', 'Quick Attack', 'Teleport', 'Screech', 'Double Team', 'Recover',
    'Harden', 'Smokescreen', 'Confuse Ray', 'Light Screen', 'Haze', 'Reflect', 'Focus Energy', 'Metronome', 'Self-Destruct', 'Lick', 'Fire Blast', 'Waterfall',
    'Swift', 'Amnesia', 'Glare', 'Leech Life', 'Splash', 'Acid Armor', 'Explosion', 'Rock Slide', 'Super Fang', 'Slash', 'Substitute', 'Flame Wheel', 'Curse',
    'Protect', 'Mach Punch', 'Sludge Bomb', 'Spikes', 'Zap Cannon', 'Perish Song', 'Icy Wind', 'Detect', 'Outrage', 'Giga Drain', 'Endure', 'Charm', 'Rollout',
    'Spark', 'Steel Wing', 'Safeguard', 'Dynamic Punch', 'Megahorn', 'Dragon Breath', 'Iron Tail', 'Metal Claw', 'Morning Sun', 'Synthesis', 'Moonlight',
    'Twister', 'Crunch', 'Extreme Speed', 'Shadow Ball', 'Future Sight', 'Rock Smash', 'Whirlpool', 'Heat Wave', 'Will-O-Wisp', 'Charge', 'Taunt', 'Wish',
    'Brick Break', 'Knock Off', 'Feather Dance', 'Hyper Voice', 'Fake Tears', 'Overheat', 'Rock Tomb', 'Metal Sound', 'Sand Tomb', 'Bullet Seed', 'Aerial Ace',
    'Iron Defense', 'Dragon Claw', 'Bulk Up', 'Bounce', 'Mud Shot', 'Volt Tackle', 'Magical Leaf', 'Calm Mind', 'Leaf Blade', 'Rock Blast', 'Water Pulse',
    'U-turn', 'Close Combat', 'Heal Block', 'Toxic Spikes', 'Aqua Ring', 'Flare Blitz', 'Aura Sphere', 'Poison Jab', 'Dark Pulse', 'Night Slash', 'Air Slash',
    'X-Scissor', 'Bug Buzz', 'Dragon Pulse', 'Dragon Rush', 'Power Gem', 'Focus Blast', 'Energy Ball', 'Brave Bird', 'Earth Power', 'Giga Impact', 'Nasty Plot',
    'Bullet Punch', 'Ice Shard', 'Shadow Claw', 'Thunder Fang', 'Ice Fang', 'Fire Fang', 'Shadow Sneak', 'Psycho Cut', 'Zen Headbutt', 'Flash Cannon', 'Draco Meteor',
    'Discharge', 'Lava Plume', 'Leaf Storm', 'Power Whip', 'Gunk Shot', 'Iron Head', 'Stone Edge', 'Stealth Rock', 'Wood Hammer', 'Aqua Jet', 'Head Smash',
    'Psyshock', 'Sludge Wave', 'Heavy Slam', 'Volt Switch', 'Bulldoze', 'Work Up', 'Electroweb', 'Wild Charge', 'Drill Run', 'Horn Leech', 'Heat Crash', 'Cotton Guard',
    'Psystrike', 'Hurricane', 'Snarl', 'Icicle Crash', 'Flying Press', 'Sticky Web', 'Phantom Force', 'Trick-Or-Treat', 'Parabolic Charge', "Forest's Curse", 'Freeze-Dry',
    'Disarming Voice', 'Parting Shot', 'Topsy-Turvy', 'Draining Kiss', 'Play Rough', 'Fairy Wind', 'Moonblast', 'Boomburst', "King's Shield", 'Diamond Storm',
    'Steam Eruption', 'Hyperspace Hole', 'Water Shuriken', 'Mystical Fire', 'Spiky Shield', 'Eerie Impulse', 'Geomancy', 'Dazzling Gleam', 'Nuzzle', 'Infestation',
    'Power-Up Punch', 'Oblivion Wing', 'Thousand Arrows', 'Thousand Waves', "Land's Wrath", 'Light of Ruin', 'Hyperspace Fury', 'Leafage', 'Lunge', 'Core Enforcer',
    'Brutal Swing', 'Liquidation', 'No Retreat', 'Breaking Swipe', 'Flip Turn', 'Nihil Light',

    'Comet Punch', 'Pay Day', 'Razor Wind', 'Sing', 'Petal Dance', 'Fissure', 'Mimic', 'Skull Bash', 'Dream Eater', 'Sky Attack', 'Spore', 'Bonemerang', 'Conversion',
    'Tri Attack', 'Conversion 2', 'False Swipe', 'Swagger', 'Ancient Power', 'Fake Out', 'Torment', 'Facade', 'Luster Purge', 'Mist Ball', 'Blaze Kick', 'Poison Fang',
    'Blast Burn', 'Hydro Cannon', 'Silver Wind', 'Shadow Punch', 'Sheer Cold', 'Muddy Water', 'Icicle Spear', 'Frenzy Plant', 'Seed Bomb', 'Drain Punch', 'Vacuum Wave',
    'Magnet Bomb', 'Charge Beam', 'Double Hit', 'Magma Storm', 'Dark Void', 'Ominous Wind', 'Storm Throw', 'Flame Charge', 'Low Sweep', 'Acid Spray', 'Scald',
    'Circle Throw', 'Frost Breath', 'Dual Chop', 'Sacred Sword', 'Techno Blast', 'Relic Song', 'Secret Sword', 'Origin Pulse', 'Precipice Blades', 'Dragon Ascent',
    'Shore Up', 'First Impression', 'Ice Hammer', 'Solar Blade', 'Fleur Cannon', 'Psychic Fangs', 'Shadow Bone', 'Spectral Thief', 'Plasma Fists', 'Double Iron Bash',
    'Octolock', 'Aura Wheel', 'Overdrive', 'Meteor Assault', 'Steel Beam', 'Scale Shot', 'Meteor Beam', 'Triple Axel', 'Dual Wingbeat', 'Scorching Sands', 'Stone Axe',
    'Barb Barrage', 'Last Respects', 'Order Up', 'Spicy Extract', 'Glaive Rush', 'Salt Cure', 'Mortal Spin', 'Make It Rain', 'Shed Tail', 'Trailblaze', 'Chilling Water',
    'Rage Fist', 'Armor Cannon', 'Bitter Blade', 'Gigaton Hammer'
].forEach(e => MOVES_ZA[e] = MOVES_ZA_NATDEX[e]);

MOVES_ZA = $.extend(true, {}, MOVES_ZA, {
    '(No Move)': { cooldown: 0 },
    'Fire Punch': { cooldown: 7 },
    'Ice Punch': { cooldown: 7 },
    'Thunder Punch': { cooldown: 7 },
    'Swords Dance': { cooldown: 15 },
    'Gust': { cooldown: 6 },
    'Wing Attack': { cooldown: 6 },
    'Whirlwind': { cooldown: 7 },
    'Fly': { cooldown: 12 },
    'Vine Whip': { cooldown: 6 },
    'Headbutt': { cooldown: 7 },
    'Tackle': { cooldown: 4 },
    'Body Slam': { cooldown: 8 },
    'Take Down': { cooldown: 8 },
    'Double-Edge': { cooldown: 10 },
    'Tail Whip': { cooldown: 7 },
    'Poison Sting': { bp: 30, cooldown: 6 },
    'Pin Missile': {
        bp: 15, hitRange: [1, 5], plusEffects: { hitRange: [1, 6] }, cooldown: 6
    },
    'Leer': { cooldown: 6 },
    'Bite': { cooldown: 6 },
    'Growl': { cooldown: 6 },
    'Roar': { cooldown: 6 },
    'Supersonic': { cooldown: 6 },
    'Ember': { cooldown: 6 },
    'Flamethrower': { cooldown: 8 },
    'Mist': { cooldown: 10 },
    'Water Gun': { cooldown: 6 },
    'Hydro Pump': { cooldown: 12 },
    'Surf': { cooldown: 8 },
    'Ice Beam': { cooldown: 8 },
    'Blizzard': { cooldown: 12 },
    'Psybeam': { cooldown: 6 },
    'Bubble Beam': { cooldown: 6 },
    'Hyper Beam': { cooldown: 20 },
    'Peck': { cooldown: 6 },
    'Absorb': { cooldown: 7 },
    'Leech Seed': { cooldown: 12 },
    'Growth': { cooldown: 15 },
    'Razor Leaf': { cooldown: 6 },
    'Solar Beam': { cooldown: 12 },
    'Poison Powder': { cooldown: 10 },
    'Stun Spore': { cooldown: 10 },
    'Sleep Powder': { cooldown: 10 },
    'String Shot': { cooldown: 9 },
    'Fire Spin': { bp: 20, cooldown: 7 },
    'Thunder Shock': { cooldown: 6 },
    'Thunderbolt': { cooldown: 8 },
    'Thunder Wave': { cooldown: 10 },
    'Thunder': { cooldown: 10 },
    'Rock Throw': { cooldown: 6 },
    'Earthquake': { cooldown: 10 },
    'Dig': { cooldown: 12 },
    'Toxic': { cooldown: 10 },
    'Confusion': { cooldown: 6 },
    'Psychic': { cooldown: 8 },
    'Hypnosis': { cooldown: 10 },
    'Agility': { cooldown: 12 },
    'Quick Attack': { bp: 30, cooldown: 3 },
    'Teleport': { cooldown: 7 },
    'Screech': { cooldown: 10 },
    'Double Team': {
        cooldown: 15, plusEffects: { cooldown: 12 }
    },
    //Recover HAS CHANGES TOO
    'Recover': { cooldown: 15 },
    'Harden': { cooldown: 6 },
    'Smokescreen': { cooldown: 10 },
    'Confuse Ray': { cooldown: 6 },
    'Light Screen': { cooldown: 12 },
    'Haze': { cooldown: 15 },
    'Reflect': { cooldown: 12 },
    'Focus Energy': { cooldown: 10 },
    'Metronome': { cooldown: 4 },
    'Self-Destruct': { cooldown: 15 },
    'Lick': { cooldown: 6 },
    'Fire Blast': { cooldown: 10 },
    'Waterfall': { cooldown: 8 },
    'Swift': { cooldown: 5 },
    'Amnesia': { cooldown: 9 },
    'Glare': { cooldown: 8 },
    'Leech Life': { cooldown: 9 },
    'Splash': { cooldown: 4 },
    'Acid Armor': { cooldown: 9 },
    'Explosion': { cooldown: 15 },
    'Rock Slide': { cooldown: 7 },
    'Super Fang': { cooldown: 9 },
    'Slash': { cooldown: 7 },
    'Substitute': { costHP: [3, 20], cooldown: 10 },
    'Flame Wheel': { cooldown: 6 },
    'Curse': { cooldown: 15 },
    'Protect': {
        cooldown: 15, plusEffects: { cooldown: 12 }
    },
    'Mach Punch': { bp: 30, cooldown: 3 },
    'Sludge Bomb': { cooldown: 7 },
    'Spikes': { cooldown: 7 },
    'Zap Cannon': { cooldown: 15 },
    'Perish Song': { cooldown: 20 },
    'Icy Wind': { cooldown: 7 },
    'Detect': {
        cooldown: 13, plusEffects: { cooldown: 10 }
    },
    'Outrage': { cooldown: 15 },
    'Giga Drain': { cooldown: 9 },
    'Endure': {
        cooldown: 12, plusEffects: { cooldown: 9 }
    },
    'Charm': { cooldown: 10 },
    'Rollout': { bp: 60, cooldown: 6 },
    'Spark': { cooldown: 6 },
    'Steel Wing': { cooldown: 7 },
    'Safeguard': { cooldown: 12 },
    'Dynamic Punch': { cooldown: 12 },
    'Megahorn': { cooldown: 10 },
    'Dragon Breath': { cooldown: 6 },
    'Iron Tail': { cooldown: 10 },
    'Metal Claw': { cooldown: 6 },
    //Morning Sun, Synthesis, Moonlight HAVE CHANGES TOO
    'Morning Sun': { cooldown: 15 },
    'Synthesis': { cooldown: 15 },
    'Moonlight': { cooldown: 15 },
    'Twister': { cooldown: 6 },
    'Crunch': { cooldown: 8 },
    'Extreme Speed': { bp: 65, cooldown: 3 },
    'Shadow Ball': { cooldown: 8 },
    'Future Sight': { cooldown: 10 },
    'Rock Smash': { cooldown: 6 },
    'Whirlpool': { bp: 20, cooldown: 7 },
    'Heat Wave': { cooldown: 9 },
    'Will-O-Wisp': { cooldown: 10 },
    'Charge': { cooldown: 10 },
    'Taunt': { cooldown: 12 },
    'Wish': { cooldown: 12 },
    'Brick Break': { cooldown: 7 },
    'Knock Off': { cooldown: 10 },
    'Feather Dance': { cooldown: 10 },
    'Hyper Voice': { cooldown: 8 },
    'Fake Tears': { cooldown: 10 },
    'Overheat': { cooldown: 10 },
    'Rock Tomb': { cooldown: 10 },
    'Metal Sound': { cooldown: 10 },
    'Sand Tomb': { bp: 20, cooldown: 7 },
    'Bullet Seed': {
        bp: 15, hitRange: [1, 5], plusEffects: { hitRange: [1, 6] }, cooldown: 6,
    },
    'Aerial Ace': { cooldown: 9 },
    'Iron Defense': { cooldown: 9 },
    'Dragon Claw': { cooldown: 8 },
    'Bulk Up': { cooldown: 18 },
    'Bounce': { cooldown: 12 },
    'Mud Shot': { cooldown: 6 },
    'Volt Tackle': { cooldown: 9 },
    'Magical Leaf': { cooldown: 6 },
    'Calm Mind': { cooldown: 18 },
    'Leaf Blade': { cooldown: 8 },
    'Rock Blast': {
        bp: 15, hitRange: [1, 5], plusEffects: { hitRange: [1, 6] }, cooldown: 6
    },
    'Water Pulse': { cooldown: 6 },
    'U-turn': { cooldown: 12 },
    'Close Combat': { cooldown: 12 },
    'Heal Block': { cooldown: 12 },
    'Toxic Spikes': { cooldown: 7 },
    'Aqua Ring': { cooldown: 10 },
    'Flare Blitz': { cooldown: 8 },
    'Aura Sphere': { cooldown: 8 },
    'Poison Jab': { cooldown: 8 },
    'Dark Pulse': { cooldown: 8 },
    'Night Slash': { cooldown: 7 },
    'Air Slash': { cooldown: 7 },
    'X-Scissor': { cooldown: 8 },
    'Bug Buzz': { cooldown: 8 },
    'Dragon Pulse': { cooldown: 8 },
    'Dragon Rush': { cooldown: 12 },
    'Power Gem': { cooldown: 8 },
    'Focus Blast': { cooldown: 12 },
    'Energy Ball': { cooldown: 8 },
    'Brave Bird': { cooldown: 10 },
    'Earth Power': { cooldown: 8 },
    'Giga Impact': { cooldown: 20 },
    'Nasty Plot': { cooldown: 15 },
    'Bullet Punch': { bp: 30, cooldown: 3 },
    'Ice Shard': { cooldown: 3 },
    'Shadow Claw': { cooldown: 7 },
    'Thunder Fang': { cooldown: 6 },
    'Ice Fang': { cooldown: 6 },
    'Fire Fang': { cooldown: 6 },
    'Shadow Sneak': { cooldown: 3 },
    'Psycho Cut': { cooldown: 7 },
    'Zen Headbutt': { cooldown: 8 },
    'Flash Cannon': { cooldown: 8 },
    'Draco Meteor': { cooldown: 10 },
    'Discharge': { cooldown: 8 },
    'Lava Plume': { cooldown: 8 },
    'Leaf Storm': { cooldown: 10 },
    'Power Whip': { cooldown: 12 },
    'Gunk Shot': { cooldown: 10 },
    'Iron Head': { cooldown: 8 },
    'Stone Edge': { cooldown: 10 },
    'Stealth Rock': { cooldown: 10 },
    'Wood Hammer': { cooldown: 10 },
    'Aqua Jet': { bp: 30, cooldown: 3 },
    'Head Smash': { cooldown: 10 },
    'Psyshock': { cooldown: 8 },
    'Sludge Wave': { cooldown: 8 },
    'Heavy Slam': { cooldown: 10 },
    'Volt Switch': { cooldown: 12 },
    'Bulldoze': { cooldown: 6 },
    'Work Up': { cooldown: 15 },
    'Electroweb': { cooldown: 7 },
    'Wild Charge': { cooldown: 8 },
    'Drill Run': { cooldown: 8 },
    'Horn Leech': { cooldown: 9 },
    'Heat Crash': { cooldown: 10 },
    'Cotton Guard': { cooldown: 10 },
    'Psystrike': { cooldown: 9 },
    'Hurricane': { cooldown: 10 },
    'Snarl': { cooldown: 9 },
    'Icicle Crash': { cooldown: 8 },
    'Flying Press': { cooldown: 9 },
    'Sticky Web': { cooldown: 7 },
    'Phantom Force': { cooldown: 12 },
    'Trick-Or-Treat': { cooldown: 10 },
    'Parabolic Charge': { cooldown: 9 },
    "Forest's Curse": { cooldown: 10 },
    'Freeze-Dry': { cooldown: 9 },
    'Disarming Voice': { cooldown: 6 },
    'Parting Shot': { cooldown: 12 },
    'Topsy-Turvy': { cooldown: 10 },
    'Draining Kiss': { cooldown: 7 },
    'Play Rough': { cooldown: 8 },
    'Fairy Wind': { cooldown: 6 },
    'Moonblast': { cooldown: 8 },
    'Boomburst': { cooldown: 12 },
    "King's Shield": {
        cooldown: 15, plusEffects: { cooldown: 12 }
    },
    'Diamond Storm': { cooldown: 10 },
    'Steam Eruption': { cooldown: 10 },
    'Hyperspace Hole': { cooldown: 8 },
    'Water Shuriken': {
        hitRange: [1, 5], plusEffects: { hitRange: 1, bp: 75 }, cooldown: 3
    },
    'Mystical Fire': { cooldown: 8 },
    'Spiky Shield': { cooldown: 15, plusEffects: { cooldown: 12 } },
    'Eerie Impulse': { cooldown: 10 },
    'Geomancy': { cooldown: 30 },
    'Dazzling Gleam': { cooldown: 8 },
    'Nuzzle': { cooldown: 6 },
    'Infestation': { cooldown: 6 },
    'Power-Up Punch': { cooldown: 10 },
    'Oblivion Wing': { cooldown: 12 },
    'Thousand Arrows': { cooldown: 10 },
    'Thousand Waves': { cooldown: 10 },
    "Land's Wrath": { cooldown: 8 },
    'Light of Ruin': { cooldown: 15 },
    'Hyperspace Fury': { cooldown: 10 },
    'Leafage': { cooldown: 6 },
    'Lunge': { cooldown: 9 },
    'Core Enforcer': { cooldown: 15 },
    'Brutal Swing': { cooldown: 6 },
    'Liquidation': { cooldown: 8 },
    'No Retreat': { cooldown: 60 },
    'Breaking Swipe': { cooldown: 9 },
    'Flip Turn': { cooldown: 12 },
    'Nihil Light': { cooldown: 15 },

    //Mega Dimension DLC
    'Comet Punch': { bp: 30, hitRange: [1, 5], cooldown: 6 },
    'Pay Day': { cooldown: 6 },
    'Razor Wind': { bp: 40, hitRange: [1, 5], cooldown: 12 },
    'Sing': { cooldown: 6 },
    'Petal Dance': { bp: 40, hitRange: 3, cooldown: 10 },
    'Fissure': { isOHKO: false, bp: 250, cooldown: 20 },
    'Mimic': { cooldown: 6 },
    'Skull Bash': { bp: 150, cooldown: 12 },
    'Dream Eater': {
        plusEffects: { drainHP: [13, 20], }, cooldown: 7
    },
    'Sky Attack': { cooldown: 10 },
    'Spore': { cooldown: 10 },
    'Bonemerang': { bp: 55, cooldown: 7 },
    'Conversion': {
        cooldown: 15, plusEffects: { cooldown: 10 }
    },
    'Tri Attack': { bp: 40, hitRange: 3, cooldown: 7 },
    'Conversion 2': {
        cooldown: 15, plusEffects: { cooldown: 10 }
    },
    'False Swipe': { cooldown: 6 },
    'Swagger': {
        cooldown: 10, plusEffects: { cooldown: 5 }
    },
    'Ancient Power': { cooldown: 6 },
    'Fake Out': {
        plusEffects: { alwaysCrit: true }, cooldown: 3
    },
    'Torment': {
        cooldown: 12, plusEffects: { cooldown: 10 }
    },
    'Facade': { cooldown: 7 },
    'Luster Purge': { cooldown: 8 },
    'Mist Ball': { cooldown: 8 },
    'Blaze Kick': { cooldown: 7 },
    'Poison Fang': { cooldown: 6 },
    'Blast Burn': { cooldown: 20 },
    'Hydro Cannon': { cooldown: 20 },
    'Silver Wind': { cooldown: 6 },
    'Shadow Punch': { cooldown: 6 },
    'Sheer Cold': { isOHKO: false, bp: 150, cooldown: 20 },
    'Muddy Water': { cooldown: 8 },
    'Icicle Spear': { hitRange: [1, 5], cooldown: 6 },
    'Frenzy Plant': { cooldown: 20 },
    'Seed Bomb': { bp: 35, hitRange: [1, 4], cooldown: 7 },
    'Drain Punch': { cooldown: 7 },
    'Vacuum Wave': { cooldown: 3 },
    'Magnet Bomb': { bp: 95, cooldown: 8 },
    'Charge Beam': { cooldown: 6 },
    'Double Hit': { bp: 50, cooldown: 6 },
    'Magma Storm': { cooldown: 12 },
    'Dark Void': {
        category: 'Special', bp: 60, drainHP: [1, 2], cooldown: 12, plusEffects: { cooldown: 9 }
    },
    'Ominous Wind': { cooldown: 6 },
    'Storm Throw': { bp: 65, cooldown: 7 },
    'Flame Charge': { cooldown: 6 },
    'Low Sweep': { cooldown: 6 },
    'Acid Spray': { cooldown: 7 },
    'Scald': { cooldown: 7 },
    'Circle Throw': { cooldown: 6 },
    'Frost Breath': { bp: 65, cooldown: 7 },
    'Dual Chop': { bp: 45, cooldown: 6 },
    'Sacred Sword': { cooldown: 8 },
    'Techno Blast': { cooldown: 12 },
    'Relic Song': { cooldown: 30 },
    'Secret Sword': { cooldown: 8 },
    'Origin Pulse': { cooldown: 16 },
    'Precipice Blades': { cooldown: 16 },
    'Dragon Ascent': { cooldown: 20 },
    'Shore Up': { cooldown: 15 },
    'First Impression': {
        plusEffects: { alwaysCrit: true }, cooldown: 6
    },
    'Ice Hammer': { cooldown: 10 },
    'Solar Blade': { cooldown: 12 },
    'Fleur Cannon': { cooldown: 10 },
    'Psychic Fangs': { cooldown: 8 },
    'Shadow Bone': { cooldown: 7 },
    'Spectral Thief': { cooldown: 15 },
    'Plasma Fists': { cooldown: 10 },
    'Double Iron Bash': { cooldown: 10 },
    'Octolock': {
        cooldown: 12, plusEffects: { cooldown: 10 }
    },
    'Aura Wheel': { cooldown: 15 },
    'Overdrive': { cooldown: 8 },
    'Meteor Assault': { cooldown: 20 },
    'Steel Beam': { cooldown: 20 },
    'Scale Shot': {
        bp: 15, hitRange: [1, 5], plusEffects: { hitRange: [1, 6] }, cooldown: 6
    },
    'Meteor Beam': { cooldown: 12 },
    'Triple Axel': { bp: 40, hitRange: 3, isTripleHit: false, cooldown: 10 },
    'Dual Wingbeat': { bp: 45, cooldown: 6 },
    'Scorching Sands': { cooldown: 7 },
    'Stone Axe': { cooldown: 10 },
    'Barb Barrage': { cooldown: 8 },
    'Last Respects': { cooldown: 8 },
    'Order Up': { cooldown: 8 },
    'Spicy Extract': { cooldown: 12 },
    'Glaive Rush': { cooldown: 12 },
    'Salt Cure': { cooldown: 8 },
    'Mortal Spin': { cooldown: 6 },
    'Make It Rain': { cooldown: 10 },
    'Shed Tail': {
        cooldown: 12, plusEffects: { cooldown: 10 }
    },
    'Trailblaze': { bp: 40, cooldown: 6 },
    'Chilling Water': { cooldown: 7 },
    'Rage Fist': { cooldown: 8 },
    'Armor Cannon': { cooldown: 12 },
    'Bitter Blade': { cooldown: 9 },
    'Gigaton Hammer': {
        cooldown: 30, plusEffects: { cooldown: 25 }
    },
});