var SETDEX_CHAMPS = {
    "Abomasnow": {
        "Sash Aurora Veil": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":220,"sd":0,"sp":36},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Snow Warning",
            "item": "Focus Sash",
            "moves": ["Blizzard","Leaf Storm","Aurora Veil","Earth Power"],
        },
        "Mixed Slow Mega": {
            "level": 50,
            "evs": {"hp":252,"at":4,"df":0,"sa":252,"sd":0,"sp":0},
            "ivs": {"sp":0},
            "nature": "Quiet",
            "item": "Abomasite",
            "moves": ["Blizzard","Energy Ball","Ice Shard","Protect"],
        },
    },
    "Absol": {
        "This is certainly a Mega that exists": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":4,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "item": "Absolite",
            "moves": ["Snarl","Dark Pulse","Ice Beam","Fire Blast"],
        },
    },
    "Aegislash": {
        "Special Leftovers Sub": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "ivs": {"at":0},
            "nature": "Modest",
            "item": "Leftovers",
            "moves": ["Shadow Ball","Flash Cannon","Substitute","King's Shield"],
        },
    },
    "Aerodactyl": {
        "Mega Offense": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Adamant",
            "item": "Aerodactylite",
            "moves": ["Rock Slide","Sky Drop","Ice Fang","Protect"],
        },
    },
    "Aggron": {
        "Mega Meme Stall": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Careful",
            "ability": "Heavy Metal",
            "item": "Aggronite",
            "moves": ["Heavy Slam","Rock Slide","Thunder Wave","Substitute"],
        },
    },
    "Alakazam": {
        "Okay who was ballin' with this Mega": {
            "level": 50,
            "evs": {"hp":228,"at":0,"df":140,"sa":4,"sd":4,"sp":132},
            "ivs": {"at":0},
            "nature": "Modest",
            "item": "Alakazite",
            "moves": ["Psychic","Dazzling Gleam","Calm Mind","Protect"],
        },
    },
    "Altaria": {
        "agano_pokemon's 24 Worlds Day 2 GravSing": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":92,"sa":4,"sd":36,"sp":124},
            "ivs": {"at":0},
            "nature": "Calm",
            "ability": "Cloud Nine",
            "item": "Mental Herb",
            "moves": ["Hurricane","Tailwind","Sing","Roost"],
        },
        "Mega Plaudent Support": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "ivs": {"at":0},
            "nature": "Calm",
            "item": "Altarianite",
            "moves": ["Dragon Pulse","Cotton Guard","Roost","Safety Goggles"],
        },
    },
    "Ampharos": {
        "What else does a Mega Ampharos do": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "ivs": {"at":0,"sp":0},
            "nature": "Quiet",
            "item": "Ampharosite",
            "moves": ["Thunderbolt","Dragon Pulse","Focus Blast","Protect"],
        },
    },
    "Araquanid": {
        "Clear Amulet TR Offense": {
            "level": 50,
            "evs": {"hp":252,"at":252,"df":4,"sa":0,"sd":0,"sp":0},
            "ivs": {"sp":0},
            "nature": "Brave",
            "item": "Clear Amulet",
            "moves": ["Liquidation","Leech Life","Lunge","Bug Bite"],
        },
        "Leftovers Infestation": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":252,"sa":0,"sd":4,"sp":0},
            "ivs": {"sp":0},
            "nature": "Relaxed",
            "item": "Leftovers",
            "moves": ["Liquidation","Infestation","Wide Guard","Protect"],
        },
    },
    "Arcanine": {
        "Tera Water Goggles": {
            "level": 50,
            "evs": {"hp":236,"at":68,"df":4,"sa":0,"sd":4,"sp":196},
            "nature": "Jolly",
            "ability": "Intimidate",
            "item": "Safety Goggles",
            "moves": ["Flare Blitz","Extreme Speed","Will-O-Wisp","Protect"],
        },
        "Tera Grass Bulky Sitrus": {
            "level": 50,
            "evs": {"hp":244,"at":52,"df":100,"sa":0,"sd":76,"sp":36},
            "nature": "Careful",
            "ability": "Intimidate",
            "item": "Sitrus Berry",
            "moves": ["Flare Blitz","Extreme Speed","Snarl","Protect"],
        },
        "Tera Normal Band": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Adamant",
            "ability": "Intimidate",
            "item": "Choice Band",
            "moves": ["Flare Blitz","Extreme Speed","Close Combat","Crunch"],
        },
        "Chuppa's & D'Angelo's San Diego 1st AV": {
            "level": 50,
            "evs": {"hp":252,"at":236,"df":4,"sa":0,"sd":12,"sp":4},
            "nature": "Adamant",
            "ability": "Intimidate",
            "item": "Assault Vest",
            "moves": ["Flare Blitz","Extreme Speed","Play Rough","Snarl"],
        },
    },
    "Archaludon": {
        "Stamina Assault Vest": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":164,"sd":68,"sp":20},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Stamina",
            "item": "Assault Vest",
            "moves": ["Flash Cannon","Draco Meteor","Electro Shot","Body Press"],
        },
        "Stellar Sturdy Power Herb": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":0,"sa":252,"sd":4,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Sturdy",
            "item": "Power Herb",
            "moves": ["Electro Shot","Flash Cannon","Draco Meteor","Dragon Pulse"],
        },
        "Electric Stalwart Power Herb": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":0,"sa":252,"sd":4,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Stalwart",
            "item": "Power Herb",
            "moves": ["Electro Shot","Thunderbolt","Draco Meteor","Dragon Pulse"],
        },
    },
    "Armarouge": {
        "Life Orb Trick Room": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Flash Fire",
            "item": "Life Orb",
            "moves": ["Expanding Force","Armor Cannon","Trick Room","Wide Guard"],
        },
        "Weak Armor WP": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Weak Armor",
            "item": "Weakness Policy",
            "moves": ["Expanding Force","Armor Cannon","Heat Wave","Endure"],
        },
        "Porengan's Stellar Meteor Beam": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Weak Armor",
            "item": "Power Herb",
            "moves": ["Expanding Force","Armor Cannon","Meteor Beam","Endure"],
        },
    },
    "Azumarill": {
        "Standard Belly Drum": {
            "level": 50,
            "evs": {"hp":244,"at":252,"df":0,"sa":0,"sd":12,"sp":0},
            "nature": "Adamant",
            "ability": "Huge Power",
            "item": "Sitrus Berry",
            "moves": ["Belly Drum","Aqua Jet","Play Rough","Protect"],
        },
        "Assault Vest Set": {
            "level": 50,
            "evs": {"hp":236,"at":236,"df":4,"sa":0,"sd":12,"sp":20},
            "nature": "Adamant",
            "ability": "Huge Power",
            "item": "Assault Vest",
            "moves": ["Aqua Jet","Play Rough","Liquidation","Ice Spinner"],
        },
    },
    "Basculegion": {
        "Banded Swift Swim": {
            "level": 50,
            "evs": {"hp":0,"at":252,"df":0,"sa":0,"sd":4,"sp":252},
            "nature": "Adamant",
            "ability": "Swift Swim",
            "item": "Choice Band",
            "moves": ["Wave Crash","Last Respects","Flip Turn","Aqua Jet"],
        },
        "Tera Ghost Sash Adaptability": {
            "level": 50,
            "evs": {"hp":0,"at":252,"df":0,"sa":0,"sd":4,"sp":252},
            "nature": "Adamant",
            "ability": "Adaptability",
            "item": "Focus Sash",
            "moves": ["Liquidation","Last Respects","Protect","Aqua Jet"],
        },
        "Scarf Adaptability": {
            "level": 50,
            "evs": {"hp":0,"at":252,"df":0,"sa":0,"sd":4,"sp":252},
            "nature": "Adamant",
            "ability": "Adaptability",
            "item": "Choice Scarf",
            "moves": ["Wave Crash","Last Respects","Flip Turn","Aqua Jet"],
        },
    },
    "Blastoise": {
        "Fast Water Spout": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Modest",
            "item": "Blastoisinite",
            "moves": ["Water Spout","Ice Beam","Aura Sphere","Water Pulse"],
        },
    },
    "Ceruledge": {
        "Bulk Up Clear Amulet": {
            "level": 50,
            "evs": {"hp":252,"at":252,"df":0,"sa":0,"sd":4,"sp":0},
            "nature": "Adamant",
            "ability": "Flash Fire",
            "item": "Clear Amulet",
            "moves": ["Bitter Blade","Shadow Sneak","Bulk Up","Protect"],
        },
    },
    "Chandelure": {
        "Tera Grass Bulky Sitrus": {
            "level": 50,
            "evs": {"hp":244,"at":0,"df":172,"sa":4,"sd":84,"sp":4},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Flash Fire",
            "item": "Sitrus Berry",
            "moves": ["Heat Wave","Shadow Ball","Will-O-Wisp","Trick Room"],
        },
        "Mega Attacker": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "item": "Chandelite",
            "moves": ["Shadow Ball","Heat Wave","Energy Ball","Protect"],
        },
    },
    "Charizard": {
        "Choice Specs Sun": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":4,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Solar Power",
            "item": "Choice Specs",
            "moves": ["Heat Wave","Overheat","Air Slash","Weather Ball"],
        },
        "Mega X DD": {
            "level": 50,
            "evs": {"hp":76,"at":252,"df":0,"sa":0,"sd":0,"sp":180},
            "nature": "Adamant",
            "item": "Charizardite X",
            "moves": ["Flare Blitz","Dragon Claw","Dragon Dance","Roost"],
        },
        "Mega Y Fast Attacker": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":0,"sa":252,"sd":4,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "item": "Charizardite Y",
            "moves": ["Heat Wave","Solar Beam","Focus Blast","Protect"],
        },
    },
    "Chesnaught": {
        "Belly Drum paired with Rillaboom": {
            "level": 50,
            "evs": {"hp":116,"at":100,"df":36,"sa":0,"sd":196,"sp":60},
            "nature": "Adamant",
            "ability": "Bulletproof",
            "item": "Sitrus Berry",
            "moves": ["Grassy Glide","Drain Punch","Belly Drum","Spiky Shield"],
        },
        "Budget(?) Ferrothorn": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "ivs": {"at":0},
            "nature": "Calm",
            "ability": "Bulletproof",
            "item": "Leftovers",
            "moves": ["Body Press","Leech Seed","Spiky Shield","Iron Defense"],
        },
    },
    "Clefable": {
        "Clefairy but a Dozo Check": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":252,"sa":0,"sd":4,"sp":0},
            "ivs": {"at":0},
            "nature": "Calm",
            "ability": "Unaware",
            "item": "Rocky Helmet",
            "moves": ["Moonblast","Follow Me","Icy Wind","Protect"],
        },
        "Mega Wall": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Calm",
            "item": "Clefablite",
            "moves": ["Moonblast","Soft-Boiled","Thunder Wave","Protect"],
        },
    },
    "Conkeldurr": {
        "Min Speed AV": {
            "level": 50,
            "evs": {"hp":116,"at":164,"df":0,"sa":0,"sd":228,"sp":0},
            "ivs": {"sp":0},
            "nature": "Brave",
            "item": "Assault Vest",
            "moves": ["Drain Punch","Mach Punch","Ice Punch","Knock Off"],
        },
    },
    "Corviknight": {
        "Bulk Up Tailwind": {
            "level": 50,
            "evs": {"hp":220,"at":204,"df":4,"sa":0,"sd":4,"sp":76},
            "nature": "Adamant",
            "ability": "Mirror Armor",
            "item": "Leftovers",
            "moves": ["Brave Bird","Tailwind","Roost","Bulk Up"],
        },
        "SoulSur Banded Corv": {
            "level": 50,
            "evs": {"hp":116,"at":252,"df":0,"sa":0,"sd":0,"sp":140},
            "nature": "Adamant",
            "ability": "Mirror Armor",
            "item": "Choice Band",
            "moves": ["Brave Bird","Tera Blast","U-turn","Iron Head"],
        },
    },
    "Delphox": {
        "Life Orb Psyspam": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":4,"sa":252,"sd":0,"sp":252},
            "ivs": {"hp":29,"at":0},
            "nature": "Timid",
            "ability": "Blaze",
            "item": "Life Orb",
            "moves": ["Heat Wave","Expanding Force","Tera Blast","Protect"],
        },
    },
    "Ditto": {
        "Min Speed Scarf": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":252,"sa":0,"sd":4,"sp":0},
            "ivs": {"at":0,"sp":0},
            "nature": "Relaxed",
            "ability": "Imposter",
            "item": "Choice Scarf",
            "moves": ["Transform"],
        },
    },
    "Dondozo": {
        "Tera Grass Oblivious": {
            "level": 50,
            "evs": {"hp":4,"at":100,"df":4,"sa":0,"sd":172,"sp":228},
            "nature": "Adamant",
            "ability": "Oblivious",
            "item": "Leftovers",
            "moves": ["Tera Blast","Earthquake","Wave Crash","Order Up"],
        },
        "45mice's 24 Worlds T16 Defense Body Press": {
            "level": 50,
            "evs": {"hp":4,"at":4,"df":196,"sa":0,"sd":148,"sp":156},
            "nature": "Impish",
            "ability": "Unaware",
            "item": "Leftovers",
            "moves": ["Body Press","Wave Crash","Order Up","Protect"],
        },
        "Kenji Yabata's 23 Worlds Cut (No Tatsu)": {
            "level": 50,
            "evs": {"hp":244,"at":4,"df":4,"sa":0,"sd":252,"sp":4},
            "nature": "Careful",
            "ability": "Unaware",
            "item": "Leftovers",
            "moves": ["Wave Crash","Fissure","Curse","Protect"],
        },
        "Mixed Life Orb": {
            "level": 50,
            "evs": {"hp":0,"at":4,"df":0,"sa":252,"sd":0,"sp":252},
            "nature": "Hasty",
            "ability": "Unaware",
            "item": "Life Orb",
            "moves": ["Surf","Wave Crash","Sleep Talk","Protect"],
        },
        "Tera Steel Bulky": {
            "level": 50,
            "evs": {"hp":116,"at":156,"df":0,"sa":0,"sd":0,"sp":236},
            "nature": "Adamant",
            "ability": "Unaware",
            "item": "Chesto Berry",
            "moves": ["Earthquake","Wave Crash","Rest","Protect"],
        },
    },
    "Dragapult": {
        "Adamant Banded Tera Dragon": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Adamant",
            "ability": "Clear Body",
            "item": "Choice Band",
            "moves": ["Dragon Darts","Outrage","Phantom Force","U-turn"],
        },
        "PokeAlex's 23 NAIC 1st Banded Tera Steel": {
            "level": 50,
            "evs": {"hp":12,"at":252,"df":4,"sa":0,"sd":28,"sp":212},
            "nature": "Jolly",
            "ability": "Clear Body",
            "item": "Choice Band",
            "moves": ["Dragon Darts","Tera Blast","Phantom Force","U-turn"],
        },
        "Choice Specs Tera Steel": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Clear Body",
            "item": "Choice Specs",
            "moves": ["Draco Meteor","Shadow Ball","Flamethrower","Tera Blast"],
        },
    },
    "Dragonite": {
        "Tera Steel Loaded Dice": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Adamant",
            "ability": "Multiscale",
            "item": "Loaded Dice",
            "moves": ["Extreme Speed","Scale Shot","Iron Head","Ice Spinner"],
        },
        "Mega Multiscale": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Adamant",
            "item": "Dragoninite",
            "moves": ["Extreme Speed","Outrage","Fire Punch","Roost"],
        },
        "Tera Normal Choice Band": {
            "level": 50,
            "evs": {"hp":236,"at":252,"df":0,"sa":0,"sd":0,"sp":20},
            "nature": "Adamant",
            "ability": "Inner Focus",
            "item": "Choice Band",
            "moves": ["Extreme Speed","Outrage","Stomping Tantrum","Aerial Ace"],
        },
        "Tera Flying Assault Vest": {
            "level": 50,
            "evs": {"hp":212,"at":252,"df":4,"sa":0,"sd":4,"sp":36},
            "nature": "Adamant",
            "ability": "Multiscale",
            "item": "Assault Vest",
            "moves": ["Extreme Speed","Tera Blast","Stomping Tantrum","Low Kick"],
        },
        "Tera Normal Assault Vest": {
            "level": 50,
            "evs": {"hp":252,"at":252,"df":0,"sa":0,"sd":0,"sp":4},
            "nature": "Adamant",
            "ability": "Inner Focus",
            "item": "Assault Vest",
            "moves": ["Extreme Speed","Aerial Ace","Stomping Tantrum","Thunder Punch"],
        },
    },
    "Empoleon": {
        "Offensive Assault Vest": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Competitive",
            "item": "Assault Vest",
            "moves": ["Flash Cannon","Water Pledge","Ice Beam","Vacuum Wave"],
        },
    },
    "Espeon": {
        "Specs Psyspam": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "item": "Choice Specs",
            "moves": ["Expanding Force","Psychic","Dazzling Gleam","Power Gem"],
        },
    },
    "Excadrill": {
        "Tera Stellar Swords Dance": {
            "level": 50,
            "evs": {"hp":0,"at":252,"df":4,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "item": "Clear Amulet",
            "moves": ["High Horsepower","Iron Head","Rock Slide","Swords Dance"],
        },
    },
    "Farigiraf": {
        "ceree's 24 Worlds 1st Tera Water Electric Seed": {
            "level": 50,
            "evs": {"hp":204,"at":0,"df":164,"sa":4,"sd":108,"sp":28},
            "ivs": {"at":0},
            "nature": "Bold",
            "ability": "Armor Tail",
            "item": "Electric Seed",
            "moves": ["Foul Play","Psychic Noise","Helping Hand","Trick Room"],
        },
        "zee's NAIC T16 Twin Beam Electric Seed": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":52,"sa":84,"sd":116,"sp":0},
            "ivs": {"at":0,"sp":22},
            "nature": "Modest",
            "ability": "Armor Tail",
            "item": "Electric Seed",
            "moves": ["Foul Play","Twin Beam","Helping Hand","Trick Room"],
        },
        "Bulky Support": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":252,"sa":0,"sd":4,"sp":0},
            "ivs": {"at":0},
            "nature": "Bold",
            "ability": "Armor Tail",
            "item": "Rocky Helmet",
            "moves": ["Dazzling Gleam","Psychic Noise","Helping Hand","Trick Room"],
        },
        "Throat Spray Offensive": {
            "level": 50,
            "evs": {"hp":108,"at":0,"df":44,"sa":156,"sd":196,"sp":4},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Armor Tail",
            "item": "Throat Spray",
            "moves": ["Hyper Voice","Psychic","Dazzling Gleam","Trick Room"],
        },
    },
    "Gallade": {
        "Trick Room Clear Amulet": {
            "level": 50,
            "evs": {"hp":252,"at":252,"df":4,"sa":0,"sd":0,"sp":0},
            "ivs": {"sp":2},
            "nature": "Brave",
            "ability": "Sharpness",
            "item": "Clear Amulet",
            "moves": ["Psycho Cut","Sacred Sword","Trick Room","Wide Guard"],
        },
        "Life Orb Max Speed": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Sharpness",
            "item": "Life Orb",
            "moves": ["Psycho Cut","Sacred Sword","Night Slash","Protect"],
        },
        "Mega Healing": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "ivs": {"at":0},
            "nature": "Sassy",
            "item": "Galladeite",
            "moves": ["Drain Punch","Night Slash","Dazzling Gleam","Protect"],
        },
    },
    "Garchomp": {
        "Clear Amulet 3 Attacks": {
            "level": 50,
            "evs": {"hp":0,"at":252,"df":0,"sa":0,"sd":4,"sp":252},
            "nature": "Jolly",
            "ability": "Rough Skin",
            "item": "Clear Amulet",
            "moves": ["Stomping Tantrum","Earthquake","Dragon Claw","Protect"],
        },
        "Fairy Loaded Dice": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Adamant",
            "ability": "Rough Skin",
            "item": "Loaded Dice",
            "moves": ["Stomping Tantrum","Earthquake","Scale Shot","Protect"],
        },
        "Tera Ground Scarf": {
            "level": 50,
            "evs": {"hp":36,"at":212,"df":4,"sa":0,"sd":4,"sp":252},
            "nature": "Adamant",
            "ability": "Rough Skin",
            "item": "Choice Scarf",
            "moves": ["Dragon Claw","Earthquake","Rock Slide","Stomping Tantrum"],
        },
        "Mega Sash": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "item": "Garchompite",
            "moves": ["Earthquake","Dragon Claw","Fire Fang","Protect"],
        },
    },
    "Gardevoir": {
        "Trick Choice Scarf": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Trace",
            "item": "Choice Scarf",
            "moves": ["Psychic","Moonblast","Dazzling Gleam","Trick"],
        },
        "Ashton's Sitrus Tera Grass": {
            "level": 50,
            "evs": {"hp":180,"at":0,"df":212,"sa":44,"sd":4,"sp":68},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Trace",
            "item": "Sitrus Berry",
            "moves": ["Psychic","Moonblast","Protect","Trick Room"],
        },
        "Mega Wall": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":252,"sa":4,"sd":0,"sp":0},
            "nature": "Bold",
            "item": "Gardevoirite",
            "moves": ["Psychic","Moonblast","Hyper Beam","Protect"],
        },
    },
    "Garganacl": {
        "Tera Ghost Body Press": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Careful",
            "ability": "Purifying Salt",
            "item": "Leftovers",
            "moves": ["Iron Defense","Body Press","Salt Cure","Recover"],
        },
        "MeLuCa's San Diego 1st Tera Poison Support": {
            "level": 50,
            "evs": {"hp":244,"at":0,"df":12,"sa":0,"sd":252,"sp":0},
            "nature": "Careful",
            "ability": "Purifying Salt",
            "item": "Leftovers",
            "moves": ["Salt Cure","Wide Guard","Protect","Recover"],
        },
    },
    "Gengar": {
        "Tera Stellar Focus Sash": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Cursed Body",
            "item": "Focus Sash",
            "moves": ["Shadow Ball","Sludge Bomb","Icy Wind","Haze"],
        },
        "Mega Wall": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":0,"sa":252,"sd":4,"sp":252},
            "nature": "Timid",
            "item": "Gengarite",
            "moves": ["Shadow Ball","Sludge Wave","Focus Blast","Protect"],
        },
    },
    "Glaceon": {
        "Specs Snow Blizzard Spam": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Snow Cloak",
            "item": "Choice Specs",
            "moves": ["Blizzard","Freeze-Dry","Tera Blast","Shadow Ball"],
        },
    },
    "Glimmora": {
        "Standard Meteor Beam": {
            "level": 50,
            "evs": {"hp":20,"at":0,"df":36,"sa":156,"sd":44,"sp":252},
            "nature": "Timid",
            "ability": "Toxic Debris",
            "item": "Power Herb",
            "moves": ["Meteor Beam","Sludge Bomb","Earth Power","Mortal Spin"],
        },
        "Tera Grass Assault Vest": {
            "level": 50,
            "evs": {"hp":212,"at":0,"df":4,"sa":156,"sd":124,"sp":12},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Toxic Debris",
            "item": "Assault Vest",
            "moves": ["Power Gem","Sludge Bomb","Earth Power","Energy Ball"],
        },
        "Emilio's Specs Tera Grass": {
            "level": 50,
            "evs": {"hp":20,"at":0,"df":0,"sa":236,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Toxic Debris",
            "item": "Choice Specs",
            "moves": ["Power Gem","Sludge Bomb","Earth Power","Sludge Wave"],
        },
    },
    "Gliscor": {
        "Tera Water Poison Heal": {
            "level": 50,
            "evs": {"hp":0,"at":252,"df":0,"sa":0,"sd":4,"sp":252},
            "nature": "Adamant",
            "item": "Toxic Orb",
            "moves": ["High Horsepower","Dual Wingbeat","Facade","Earthquake"],
        },
    },
    "Goodra": {
        "Tera Water Assault Vest": {
            "level": 50,
            "evs": {"hp":204,"at":0,"df":36,"sa":236,"sd":28,"sp":4},
            "nature": "Modest",
            "ability": "Sap Sipper",
            "item": "Assault Vest",
            "moves": ["Draco Meteor","Muddy Water","Acid Spray","Flamethrower"],
        },
    },
    "Greninja": {
        "Loaded Dice Arch Enabler": {
            "level": 50,
            "evs": {"hp":212,"at":0,"df":4,"sa":4,"sd":36,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Torrent",
            "item": "Loaded Dice",
            "moves": ["Water Shuriken","Dark Pulse","Icy Wind","Haze"],
        },
        "Choice Specs Protean": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":0,"sa":252,"sd":4,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Protean",
            "item": "Choice Specs",
            "moves": ["Water Shuriken","Grass Knot","Dark Pulse","Ice Beam"],
        },
    },
    "Grimmsnarl": {
        "Screens Light Clay": {
            "level": 50,
            "evs": {"hp":252,"at":4,"df":124,"sa":0,"sd":116,"sp":12},
            "nature": "Careful",
            "ability": "Prankster",
            "item": "Light Clay",
            "moves": ["Spirit Break","Reflect","Light Screen","Foul Play"],
        },
    },
    "Gyarados": {
        "Tera Steel Bulky Support": {
            "level": 50,
            "evs": {"hp":252,"at":20,"df":76,"sa":0,"sd":156,"sp":4},
            "nature": "Careful",
            "ability": "Intimidate",
            "item": "Sitrus Berry",
            "moves": ["Waterfall","Iron Head","Taunt","Thunder Wave"],
        },
        "Tera Flying Dragon Dance": {
            "level": 50,
            "evs": {"hp":0,"at":252,"df":0,"sa":0,"sd":4,"sp":252},
            "nature": "Jolly",
            "ability": "Intimidate",
            "item": "Clear Amulet",
            "moves": ["Waterfall","Tera Blast","Dragon Dance","Protect"],
        },
    },
        "Mega Intimidate": {
            "level": 50,
            "evs": {"hp":252,"at":4,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Adamant",
            "item": "Gyaradosite",
            "moves": ["Waterfall","Earthquake","Bounce","Protect"],
        },
    
    "Hatterene": {
        "Tera Fire Trick Room": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":252,"sd":0,"sp":0},
            "ivs": {"at":0,"sp":0},
            "nature": "Quiet",
            "ability": "Magic Bounce",
            "item": "Life Orb",
            "moves": ["Expanding Force","Dazzling Gleam","Mystical Fire","Trick Room"],
        },
    },
    "Heracross": {
        "Mega Attacker in Tailwind": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Adamant",
            "ability": "Moxie",
            "item": "Heracronite",
            "moves": ["Pin Missile","Close Combat","Rock Blast","Protect"],
        },
    },
    "Hippowdon": {
        "Stall Chipper": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Impish",
            "item": "Rocky Helmet",
            "moves": ["Sand Tomb","Body Press","Slack Off","Yawn"],
        },
    },
    "Houndoom": {
        "If you REALLY hate Hisuian Typhlosion": {
            "level": 50,
            "evs": {"hp":84,"at":0,"df":4,"sa":188,"sd":4,"sp":228},
            "ivs": {"at":0},
            "nature": "Timid",
            "item": "Safety Goggles",
            "moves": ["Dark Pulse","Snarl","Overheat","Protect"],
        },
    },
        "Mega Attacker": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "item": "Houndoominite",
            "moves": ["Fire Blast","Dark Pulse","Sucker Punch","Protect"],
        },
    
    "Hydrapple": {
        "Offensive Assault Vest": {
            "level": 50,
            "evs": {"hp":228,"at":0,"df":4,"sa":236,"sd":28,"sp":12},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Regenerator",
            "item": "Assault Vest",
            "moves": ["Giga Drain","Fickle Beam","Earth Power","Pollen Puff"],
        },
    },
    "Hydreigon": {
        "Tera Fire Life Orb": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Levitate",
            "item": "Life Orb",
            "moves": ["Dark Pulse","Draco Meteor","Heat Wave","Tailwind"],
        },
        "Tera Steel Assault Vest": {
            "level": 50,
            "evs": {"hp":188,"at":0,"df":20,"sa":116,"sd":12,"sp":172},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Levitate",
            "item": "Assault Vest",
            "moves": ["Dark Pulse","Draco Meteor","Snarl","Flash Cannon"],
        },
    },
    "Incineroar": {
        "Max Speed Safety Goggles": {
            "level": 50,
            "evs": {"hp":244,"at":4,"df":4,"sa":0,"sd":4,"sp":252},
            "nature": "Jolly",
            "ability": "Intimidate",
            "item": "Safety Goggles",
            "moves": ["Flare Blitz","Knock Off","Fake Out","Parting Shot"],
        },
        "Tera Grass Assault Vest": {
            "level": 50,
            "evs": {"hp":228,"at":0,"df":188,"sa":0,"sd":92,"sp":0},
            "nature": "Impish",
            "ability": "Intimidate",
            "item": "Assault Vest",
            "moves": ["Flare Blitz","Knock Off","Fake Out","U-turn"],
        },
        "Physically Defensive Rocky Helmet": {
            "level": 50,
            "evs": {"hp":244,"at":4,"df":196,"sa":0,"sd":52,"sp":12},
            "nature": "Impish",
            "ability": "Intimidate",
            "item": "Rocky Helmet",
            "moves": ["Knock Off","Fake Out","Will-O-Wisp","Parting Shot"],
        },
        "Ol' Reliable Bulky Sitrus": {
            "level": 50,
            "evs": {"hp":236,"at":44,"df":20,"sa":0,"sd":124,"sp":84},
            "nature": "Careful",
            "ability": "Intimidate",
            "item": "Sitrus Berry",
            "moves": ["Flare Blitz","Knock Off","Fake Out","Parting Shot"],
        },
    },
    "Kangaskhan": {
        "Fake Out + 3 Attacks": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "item": "Kangaskhanite",
            "moves": ["Fake Out","Power-Up Punch","Return","Sucker Punch"],
        },
        "Protect PUP": {
            "level": 50,
            "evs": {"hp":212,"at":132,"df":4,"sa":0,"sd":100,"sp":60},
            "nature": "Adamant",
            "item": "Kangaskhanite",
            "moves": ["Power-Up Punch","Return","Sucker Punch","Protect"],
        },
        "2014 Slow Hammer Arm": {
            "level": 50,
            "evs": {"hp":252,"at":252,"df":0,"sa":0,"sd":4,"sp":0},
            "nature": "Adamant",
            "item": "Kangaskhanite",
            "moves": ["Double-Edge","Hammer Arm","Sucker Punch","Protect"],
        },
    },
    "Kingambit": {
        "Black Glasses SUGGESTION BY ASHTONCOXGAZ": {
            "level": 50,
            "evs": {"hp":252,"at":252,"df":0,"sa":0,"sd":4,"sp":0},
            "nature": "Adamant",
            "ability": "Defiant",
            "item": "Black Glasses",
            "moves": ["Kowtow Cleave","Sucker Punch","Iron Head","Assurance"],
        },
        "Assault Vest Tera Fire": {
            "level": 50,
            "evs": {"hp":188,"at":252,"df":4,"sa":0,"sd":60,"sp":4},
            "nature": "Adamant",
            "ability": "Defiant",
            "item": "Assault Vest",
            "moves": ["Kowtow Cleave","Iron Head","Sucker Punch","Low Kick"],
        },
    },
    "Kleavor": {
        "Scarf Max Speed": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Sharpness",
            "item": "Choice Scarf",
            "moves": ["Stone Axe","U-turn","X-Scissor","Close Combat"],
        },
    },
    "Klefki": {
        "Screens Speed Control": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":76,"sa":0,"sd":180,"sp":0},
            "ivs": {"at":0},
            "nature": "Calm",
            "ability": "Prankster",
            "item": "Light Clay",
            "moves": ["Dazzling Gleam","Reflect","Light Screen","Thunder Wave"],
        },
    },
    "Krookodile": {
        "Tera Poison Amulet Offense": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "item": "Clear Amulet",
            "moves": ["Knock Off","High Horsepower","Earthquake","Gunk Shot"],
        },
    },
    "Lucario": {
        "Tera Stellar Sash Offense": {
            "level": 50,
            "evs": {"hp":0,"at":252,"df":0,"sa":0,"sd":4,"sp":252},
            "nature": "Jolly",
            "item": "Focus Sash",
            "moves": ["Close Combat","Meteor Mash","Extreme Speed","Detect"],
        },
        "Mega Wall": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Bold",
            "item": "Lucarionite",
            "moves": ["Close Combat","Meteor Mash","Flash Cannon","Protect"],
        },
    },
    "Mamoswine": {
        "Offensive Sash": {
            "level": 50,
            "evs": {"hp":0,"at":252,"df":0,"sa":0,"sd":4,"sp":252},
            "nature": "Adamant",
            "ability": "Oblivious",
            "item": "Focus Sash",
            "moves": ["Icicle Crash","High Horsepower","Ice Shard","Rock Slide"],
        },
    },
    "Maushold": {
        "Bulky Goggles Support": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":156,"sa":0,"sd":100,"sp":0},
            "nature": "Impish",
            "ability": "Friend Guard",
            "item": "Safety Goggles",
            "moves": ["Super Fang","Feint","Beat Up","Follow Me"],
        },
        "Wide Lens Technician": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Technician",
            "item": "Wide Lens",
            "moves": ["Population Bomb","Follow Me","Protect","Bite"],
        },
    },
    "Mega Absol Z": {
        "Z-Celebrate": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "item": "Absolite Z",
            "moves": ["Sucker Punch","Play Rough","Iron Tail","Swords Dance"],
        },
    },
    "Mega Garchomp Z": {
        "Dragon Dance": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "item": "Garchompite Z",
            "moves": ["Dragon Claw","Earthquake","Stone Edge","Dragon Dance"],
        },
    },
    "Mega Lucario Z": {
        "Special Attacker": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":0,"sa":252,"sd":4,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "item": "Lucarionite Z",
            "moves": ["Aura Sphere","Flash Cannon","Vacuum Wave","Nasty Plot"],
        },
    },
    "Mega Raichu X": {
        "Mega Offense": {
            "level": 50,
            "evs": {"hp":0,"at":252,"df":0,"sa":0,"sd":4,"sp":252},
            "nature": "Jolly",
            "item": "Raichunite X",
            "moves": ["Thunder Punch","Volt Tackle","Psychic Fangs","Iron Tail"],
        },
    },
    "Mega Raichu Y": {
        "Mega Offense": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":0,"sa":252,"sd":4,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "item": "Raichunite Y",
            "moves": ["Thunder","Psychic","Nuzzle","Focus Blast"],
        },
    },
    "Meowscarada": {
        "Sash Overgrow": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Overgrow",
            "item": "Focus Sash",
            "moves": ["Flower Trick","Knock Off","Sucker Punch","Triple Axel"],
        },
        "Choice Band Protean": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Protean",
            "item": "Choice Band",
            "moves": ["Flower Trick","Knock Off","Triple Axel","U-turn"],
        },
    },
    "Metagross": {
        "Assault Vest Set": {
            "level": 50,
            "evs": {"hp":252,"at":252,"df":0,"sa":0,"sd":0,"sp":4},
            "nature": "Adamant",
            "item": "Assault Vest",
            "moves": ["Heavy Slam","Psychic Fangs","Bullet Punch","Stomping Tantrum"],
        },
    },
        "Mega Wall": {
            "level": 50,
            "evs": {"hp":252,"at":4,"df":0,"sa":0,"sd":252,"sp":0},
            "nature": "Adamant",
            "item": "Metagrossite",
            "moves": ["Meteor Mash","Earthquake","Hammer Arm","Protect"],
        },
    
    "Milotic": {
        "Bulky Icy Wind Support": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":252,"sa":4,"sd":0,"sp":0},
            "ivs": {"at":0},
            "nature": "Bold",
            "ability": "Competitive",
            "item": "Leftovers",
            "moves": ["Scald","Icy Wind","Ice Beam","Hydro Pump"],
        },
    },
    "Mimikyu": {
        "Trick Room Safety Goggles": {
            "level": 50,
            "evs": {"hp":252,"at":164,"df":44,"sa":0,"sd":36,"sp":12},
            "nature": "Adamant",
            "ability": "Disguise",
            "item": "Safety Goggles",
            "moves": ["Play Rough","Shadow Sneak","Trick Room","Will-O-Wisp"],
        },
        "Tera Ghost Life Orb": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Adamant",
            "ability": "Disguise",
            "item": "Life Orb",
            "moves": ["Play Rough","Shadow Sneak","Shadow Claw","Protect"],
        },
    },
    "Mudsdale": {
        "Stamina Assault Vest": {
            "level": 50,
            "evs": {"hp":252,"at":196,"df":0,"sa":0,"sd":60,"sp":0},
            "ivs": {"sp":0},
            "nature": "Brave",
            "ability": "Stamina",
            "item": "Assault Vest",
            "moves": ["High Horsepower","Body Press","Rock Slide","Heavy Slam"],
        },
    },
    "Ninetales": {
        "Eject Pack Support": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":4,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Drought",
            "item": "Eject Pack",
            "moves": ["Overheat","Scorching Sands","Roar","Will-O-Wisp"],
        },
    },
    "Noivern": {
        "Tera Normal Boomburst": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Frisk",
            "item": "Focus Sash",
            "moves": ["Boomburst","Draco Meteor","Heat Wave","Tailwind"],
        },
    },
    "Oranguru": {
        "Safety Goggles Trick Room": {
            "level": 50,
            "evs": {"hp":244,"at":0,"df":108,"sa":0,"sd":156,"sp":0},
            "ivs": {"at":0,"sp":0},
            "nature": "Sassy",
            "ability": "Inner Focus",
            "item": "Safety Goggles",
            "moves": ["Foul Play","Trick Room","Instruct","Protect"],
        },
    },
    "Orthworm": {
        "Body Press Shed Tail": {
            "level": 50,
            "evs": {"hp":244,"at":0,"df":36,"sa":0,"sd":228,"sp":0},
            "nature": "Careful",
            "ability": "Earth Eater",
            "item": "Leftovers",
            "moves": ["Body Press","Heavy Slam","Shed Tail","Iron Defense"],
        },
    },
    "Palafin": {
        "Mystic Water Haze": {
            "level": 50,
            "evs": {"hp":252,"at":252,"df":0,"sa":0,"sd":0,"sp":4},
            "nature": "Adamant",
            "ability": "Zero to Hero",
            "item": "Mystic Water",
            "moves": ["Jet Punch","Wave Crash","Haze","Protect"],
        },
        "Choice Band Max Speed": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Zero to Hero",
            "item": "Choice Band",
            "moves": ["Flip Turn","Jet Punch","Ice Punch","Close Combat"],
        },
    },
    "Pawmot": {
        "Basic Focus Sash": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Natural Cure",
            "item": "Focus Sash",
            "moves": ["Fake Out","Double Shock","Close Combat","Revival Blessing"],
        },
    },
    "Pelipper": {
        "Tera Stellar Sash": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Drizzle",
            "item": "Focus Sash",
            "moves": ["Hurricane","Tailwind","Wide Guard","Weather Ball"],
        },
        "Slow Life Orb": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Drizzle",
            "item": "Life Orb",
            "moves": ["Hurricane","Weather Ball","Wide Guard","Protect"],
        },
        "Max Speed Scarf": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Drizzle",
            "item": "Choice Scarf",
            "moves": ["Hurricane","Muddy Water","Ice Beam","Weather Ball"],
        },
        "Bulky Damp Rock": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":76,"sa":4,"sd":140,"sp":36},
            "ivs": {"at":0},
            "nature": "Bold",
            "ability": "Drizzle",
            "item": "Damp Rock",
            "moves": ["Hurricane","Tailwind","Wide Guard","Weather Ball"],
        },
    },
    "Pinsir": {
        "The 2014 Aerilate Mega": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Moxie",
            "item": "Pinsirite",
            "moves": ["Return","Earthquake","Feint","Swords Dance"],
        },
    },
    "Politoed": {
        "Bulky Rain Support": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Drizzle",
            "item": "Sitrus Berry",
            "moves": ["Muddy Water","Icy Wind","Weather Ball","Helping Hand"],
        },
    },
    "Primarina": {
        "Tera Poison Sitrus": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Liquid Voice",
            "item": "Sitrus Berry",
            "moves": ["Hyper Voice","Moonblast","Dazzling Gleam","Water Pledge"],
        },
    },
    "Quaquaval": {
        "Clear Amulet Set": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Moxie",
            "item": "Clear Amulet",
            "moves": ["Aqua Step","Close Combat","Ice Spinner","Flip Turn"],
        },
    },
    "Raichu": {
        "Basic Focus Sash": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":4,"sd":0,"sp":252},
            "nature": "Timid",
            "ability": "Lightning Rod",
            "item": "Focus Sash",
            "moves": ["Fake Out","Nuzzle","Volt Switch","Endeavor"],
        },
    },
    "Rhyperior": {
        "Weakness Policy TR Offense": {
            "level": 50,
            "evs": {"hp":68,"at":244,"df":0,"sa":0,"sd":196,"sp":0},
            "ivs": {"sp":0},
            "nature": "Brave",
            "ability": "Solid Rock",
            "item": "Weakness Policy",
            "moves": ["Rock Slide","Earthquake","Drill Run","Ice Punch"],
        },
    },
    "Sableye": {
        "Quash Will-O-Wisp": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":116,"sa":0,"sd":140,"sp":0},
            "ivs": {"at":0},
            "nature": "Bold",
            "ability": "Prankster",
            "item": "Roseli Berry",
            "moves": ["Foul Play","Fake Out","Quash","Will-O-Wisp"],
        },
    },
        "Mega Wall": {
            "level": 50,
            "evs": {"hp":252,"at":4,"df":252,"sa":0,"sd":0,"sp":0},
            "nature": "Bold",
            "item": "Sablenite",
            "moves": ["Foul Play","Night Shade","Recover","Protect"],
        },
    
    "Scizor": {
        "Tera Steel Swords Dance": {
            "level": 50,
            "evs": {"hp":252,"at":252,"df":0,"sa":0,"sd":4,"sp":0},
            "nature": "Adamant",
            "ability": "Technician",
            "item": "Clear Amulet",
            "moves": ["Bullet Punch","Close Combat","Swords Dance","Protect"],
        },
        "Tera Steel Choice Band": {
            "level": 50,
            "evs": {"hp":252,"at":252,"df":0,"sa":0,"sd":4,"sp":0},
            "nature": "Adamant",
            "ability": "Technician",
            "item": "Choice Band",
            "moves": ["Bullet Punch","Close Combat","Bug Bite","U-turn"],
        },
    },
        "Mega Wall": {
            "level": 50,
            "evs": {"hp":248,"at":0,"df":72,"sa":0,"sd":188,"sp":0},
            "nature": "Careful",
            "item": "Scizorite",
            "moves": ["Bullet Punch","U-turn","Superpower","Roost"],
        },
    
    "Scovillain": {
        "Offensive Chlorophyll": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Chlorophyll",
            "item": "Focus Sash",
            "moves": ["Flamethrower","Energy Ball","Pollen Puff","Spicy Extract"],
        },
    },
    "Serperior": {
        "Jamie Boyt Spread with Tera Fire": {
            "level": 50,
            "evs": {"hp":116,"at":0,"df":4,"sa":132,"sd":4,"sp":252},
            "nature": "Timid",
            "ability": "Contrary",
            "item": "Wide Lens",
            "moves": ["Leaf Storm","Tera Blast","Dragon Pulse","Giga Drain"],
        },
    },
    "Sinistcha": {
        "Trick Room Support": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":84,"sa":4,"sd":156,"sp":12},
            "ivs": {"at":0},
            "nature": "Calm",
            "item": "Sitrus Berry",
            "moves": ["Matcha Gotcha","Rage Powder","Strength Sap","Trick Room"],
        },
    },
    "Skeledirge": {
        "Bulky Tera Grass": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Unaware",
            "item": "Leftovers",
            "moves": ["Torch Song","Shadow Ball","Slack Off","Protect"],
        },
    },
    "Slowbro": {
        "Trick Room Support": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":252,"sa":0,"sd":4,"sp":0},
            "ivs": {"at":0,"sp":0},
            "nature": "Relaxed",
            "ability": "Oblivious",
            "item": "Leftovers",
            "moves": ["Scald","Psychic","Body Press","Trick Room"],
        },
    },
        "Mega Wall": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":252,"sa":0,"sd":4,"sp":0},
            "nature": "Bold",
            "item": "Slowbronite",
            "moves": ["Scald","Psyshock","Slack Off","Teleport"],
        },
    
    "Slowking": {
        "Basic Trick Room": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":108,"sa":108,"sd":36,"sp":0},
            "ivs": {"at":0,"sp":0},
            "nature": "Quiet",
            "ability": "Regenerator",
            "item": "Sitrus Berry",
            "moves": ["Psychic","Hydro Pump","Trick Room","Helping Hand"],
        },
    },
    "Sneasler": {
        "Swords Dance Grassy Seed Acrobatics": {
            "level": 50,
            "evs": {"hp":172,"at":92,"df":108,"sa":0,"sd":4,"sp":132},
            "nature": "Adamant",
            "item": "Grassy Seed",
            "moves": ["Acrobatics","Close Combat","Swords Dance","Protect"],
        },
        "Tera Dark Unburden Dark Move": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Adamant",
            "item": "Psychic Seed",
            "moves": ["Dire Claw","Close Combat","Throat Chop","Lash Out"],
        },
        "Tera Stellar Sash": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Poison Touch",
            "item": "Focus Sash",
            "moves": ["Dire Claw","Close Combat","Throat Chop","Fake Out"],
        },
    },
    "Snorlax": {
        "Leftovers Thick Fat": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":252,"sa":0,"sd":0,"sp":0},
            "nature": "Adamant",
            "ability": "Thick Fat",
            "item": "Leftovers",
            "moves": ["Heavy Slam","Heat Crash","High Horsepower","Double-Edge"],
        },
    },
    "Sylveon": {
        "Tera Water Choice Specs": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "nature": "Modest",
            "ability": "Pixilate",
            "item": "Choice Specs",
            "moves": ["Hyper Voice","Tera Blast","Quick Attack","Hyper Beam"],
        },
        "Tera Fire Throat Spray": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "nature": "Modest",
            "ability": "Pixilate",
            "item": "Throat Spray",
            "moves": ["Hyper Voice","Tera Blast","Quick Attack","Protect"],
        },
    },
    "Talonflame": {
        "Bulky Tera Ghost Cloak": {
            "level": 50,
            "evs": {"hp":204,"at":36,"df":180,"sa":0,"sd":4,"sp":84},
            "nature": "Jolly",
            "ability": "Gale Wings",
            "item": "Covert Cloak",
            "moves": ["Brave Bird","Flare Blitz","Taunt","Tailwind"],
        },
        "Tera Flying Sharp Beak": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Gale Wings",
            "item": "Sharp Beak",
            "moves": ["Brave Bird","Tailwind","Taunt","Protect"],
        },
    },
    "Tatsugiri": {
        "Standard Choice Scarf": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":0,"sa":252,"sd":4,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Commander",
            "item": "Choice Scarf",
            "moves": ["Muddy Water","Draco Meteor","Icy Wind","Dragon Pulse"],
        },
        "Standard Sash": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":0,"sa":252,"sd":4,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Commander",
            "item": "Focus Sash",
            "moves": ["Muddy Water","Draco Meteor","Taunt","Protect"],
        },
    },
    "Tinkaton": {
        "Assault Vest Own Tempo": {
            "level": 50,
            "evs": {"hp":252,"at":252,"df":0,"sa":0,"sd":4,"sp":0},
            "nature": "Adamant",
            "ability": "Own Tempo",
            "item": "Assault Vest",
            "moves": ["Fake Out","Gigaton Hammer","Play Rough","Knock Off"],
        },
    },
    "Torkoal": {
        "Tera Fire Charcoal": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "ivs": {"at":0,"sp":0},
            "nature": "Quiet",
            "ability": "Drought",
            "item": "Charcoal",
            "moves": ["Eruption","Heat Wave","Earth Power","Protect"],
        },
    },
    "Tsareena": {
        "Tera Ice Wide Lens": {
            "level": 50,
            "evs": {"hp":52,"at":236,"df":4,"sa":0,"sd":4,"sp":212},
            "nature": "Adamant",
            "ability": "Queenly Majesty",
            "item": "Wide Lens",
            "moves": ["Power Whip","Triple Axel","Low Kick","U-turn"],
        },
    },
    "Typhlosion": {
        "Scarf Eruption": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Flash Fire",
            "item": "Choice Scarf",
            "moves": ["Heat Wave","Eruption","Overheat","Tera Blast"],
        },
    },
    "Tyranitar": {
        "Tera Flying AV": {
            "level": 50,
            "evs": {"hp":196,"at":140,"df":12,"sa":0,"sd":28,"sp":132},
            "nature": "Adamant",
            "ability": "Sand Stream",
            "item": "Assault Vest",
            "moves": ["Rock Slide","Knock Off","Low Kick","Tera Blast"],
        },
        "EternalSnowman's Sacramento 1st Psychic AV": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":4,"sa":0,"sd":4,"sp":244},
            "nature": "Adamant",
            "ability": "Sand Stream",
            "item": "Assault Vest",
            "moves": ["Rock Slide","Knock Off","Low Kick","Tera Blast"],
        },
        "Tera Grass AV Lentar": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Careful",
            "ability": "Sand Stream",
            "item": "Assault Vest",
            "moves": ["Rock Slide","Knock Off","Low Kick","Tera Blast"],
        },
        "Dragon Dance Life Orb": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Sand Stream",
            "item": "Life Orb",
            "moves": ["Rock Slide","Crunch","Dragon Dance","Protect"],
        },
    },
        "Mega Wall": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Careful",
            "item": "Tyranitarite",
            "moves": ["Stone Edge","Crunch","Ice Punch","Protect"],
        },
    
    "Umbreon": {
        "Tera Water Support": {
            "level": 50,
            "evs": {"hp":244,"at":0,"df":228,"sa":0,"sd":36,"sp":0},
            "ivs": {"at":0},
            "nature": "Calm",
            "ability": "Inner Focus",
            "item": "Leftovers",
            "moves": ["Foul Play","Snarl","Taunt","Yawn"],
        },
    },
    "Ursaluna": {
        "Trick Room Guts": {
            "level": 50,
            "evs": {"hp":252,"at":252,"df":0,"sa":0,"sd":4,"sp":0},
            "ivs": {"sp":0},
            "nature": "Brave",
            "item": "Flame Orb",
            "moves": ["Facade","Headlong Rush","Earthquake","Ice Punch"],
        },
    },
    "Vaporeon": {
        "Hard Dondozo Check": {
            "level": 50,
            "evs": {"hp":148,"at":0,"df":252,"sa":4,"sd":100,"sp":4},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Water Absorb",
            "item": "Leftovers",
            "moves": ["Muddy Water","Ice Beam","Haze","Recover"],
        },
    },
    "Venusaur": {
        "Tera Ghost Sash Sleep Powder": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Chlorophyll",
            "item": "Focus Sash",
            "moves": ["Grass Knot","Sludge Bomb","Sleep Powder","Protect"],
        },
        "Offensive Life Orb": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Chlorophyll",
            "item": "Life Orb",
            "moves": ["Leaf Storm","Sludge Bomb","Earth Power","Tera Blast"],
        },
        "Mega Wall": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":124,"sa":76,"sd":52,"sp":4},
            "ivs": {"at":0},
            "nature": "Bold",
            "item": "Venusaurite",
            "moves": ["Giga Drain","Sludge Bomb","Leech Seed","Protect"],
        },
        "Mega Wall": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":140,"sd":0,"sp":116},
            "ivs": {"at":0,"df":30},
            "nature": "Modest",
            "item": "Venusaurite",
            "moves": ["Giga Drain","Sludge Bomb","Sleep Powder","Hidden Power Ice"],
        },
    },
    "Vivillon": {
        "Compound Eyes Hurricane Sleep Powder": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Compound Eyes",
            "item": "Focus Sash",
            "moves": ["Hurricane","Pollen Puff","Rage Powder","Sleep Powder"],
        },
        "Friend Guard Tailwind": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Friend Guard",
            "item": "Focus Sash",
            "moves": ["Pollen Puff","Tailwind","Rage Powder","Sleep Powder"],
        },
    },
    "Volcarona": {
        "Leftovers Quiver Dance": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":60,"sa":36,"sd":4,"sp":156},
            "ivs": {"at":0},
            "nature": "Modest",
            "ability": "Flame Body",
            "item": "Leftovers",
            "moves": ["Fiery Dance","Giga Drain","Heat Wave","Quiver Dance"],
        },
        "Sitrus Berry Support": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":212,"sa":4,"sd":36,"sp":4},
            "ivs": {"at":0},
            "nature": "Calm",
            "ability": "Flame Body",
            "item": "Sitrus Berry",
            "moves": ["Struggle Bug","Overheat","Tailwind","Rage Powder"],
        },
    },
    "Weavile": {
        "4 Attacks Focus Sash": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "ability": "Pressure",
            "item": "Focus Sash",
            "moves": ["Fake Out","Triple Axel","Knock Off","Upper Hand"],
        },
    },
    "Whimsicott": {
        "Sash Tailwind": {
            "level": 50,
            "evs": {"hp":4,"at":0,"df":0,"sa":252,"sd":0,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Prankster",
            "item": "Focus Sash",
            "moves": ["Moonblast","Energy Ball","Tailwind","Sunny Day"],
        },
        "Bulky Covert Cloak": {
            "level": 50,
            "evs": {"hp":156,"at":0,"df":0,"sa":0,"sd":204,"sp":148},
            "ivs": {"at":0},
            "nature": "Timid",
            "ability": "Prankster",
            "item": "Covert Cloak",
            "moves": ["Moonblast","Light Screen","Tailwind","Encore"],
        },
    },
    "Alcremie": {
        "Sweet Veil": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Calm",
            "item": "Leftovers",
            "moves": ["Dazzling Gleam","Decorate","Recover","Acid Armor"],
        },
    },
    "Appletun": {
        "Thick Fat": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Bold",
            "item": "Leftovers",
            "moves": ["Apple Acid","Recover","Body Press","Curse"],
        },
    },
    "Crabominable": {
        "Iron Fist": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Adamant",
            "item": "Choice Band",
            "moves": ["Ice Hammer","Close Combat","Earthquake","Crabhammer"],
        },
    },
    "Decidueye": {
        "Arrow Shot": {
            "level": 50,
            "evs": {"hp":0,"at":252,"df":0,"sa":0,"sd":4,"sp":252},
            "nature": "Jolly",
            "item": "Choice Band",
            "moves": ["Spirit Shackle","Leaf Blade","U-turn","Shadow Sneak"],
        },
    },
    "Drampa": {
        "Berserk": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":0,"sa":252,"sd":4,"sp":0},
            "nature": "Quiet",
            "item": "Choice Specs",
            "moves": ["Draco Meteor","Hyper Voice","Focus Blast","Tera Blast"],
        },
    },
    "Floette": {
        "Light Surge": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":0,"sa":252,"sd":4,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "item": "Light Clay",
            "moves": ["Moonblast","Reflect","Light Screen","Energy Ball"],
        },
    },
    "Gourgeist": {
        "Pressure": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Careful",
            "item": "Leftovers",
            "moves": ["Seed Bomb","Shadow Sneak","Will-O-Wisp","Pain Split"],
        },
    },
    "Lycanroc": {
        "Tough Claws": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "item": "Life Orb",
            "moves": ["Accelerock","Close Combat","Psychic Fangs","Drill Run"],
        },
    },
    "Morpeko": {
        "Hunger Switch": {
            "level": 50,
            "evs": {"hp":0,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Jolly",
            "item": "Focus Sash",
            "moves": ["Aura Wheel","Parting Shot","Super Fang","Protect"],
        },
    },
    "Polteageist": {
        "Weakness Policy": {
            "level": 50,
            "evs": {"hp":0,"at":0,"df":0,"sa":252,"sd":4,"sp":252},
            "ivs": {"at":0},
            "nature": "Timid",
            "item": "Weakness Policy",
            "moves": ["Shadow Ball","Giga Drain","Stored Power","Shell Smash"],
        },
    },
    "Runerigus": {
        "Wall": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Relaxed",
            "item": "Leftovers",
            "moves": ["Earthquake","Shadow Ball","Stealth Rock","Curse"],
        },
    },
    "Sandaconda": {
        "Sand Spit": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Sassy",
            "item": "Leftovers",
            "moves": ["Earthquake","Stealth Rock","Glare","Protect"],
        },
    },
    "Toucannon": {
        "Skill Link": {
            "level": 50,
            "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
            "nature": "Adamant",
            "item": "Focus Sash",
            "moves": ["Beak Blast","Bullet Seed","Brave Bird","Rock Blast"],
        },
    },
    "Toxapex": {
        "Regenerator": {
            "level": 50,
            "evs": {"hp":252,"at":0,"df":4,"sa":0,"sd":252,"sp":0},
            "nature": "Calm",
            "item": "Black Sludge",
            "moves": ["Scald","Haze","Recover","Toxic"],
        },
    },

    "Mega Venusaur": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Charizard X": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Charizard Y": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Blastoise": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Clefable": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Ninetales": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Gengar": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Kangaskhan": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Pinsir": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Gyarados": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Aerodactyl": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Dragonite": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Ampharos": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Scizor": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Heracross": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Sableye": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Gardevoir": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Aggron": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Tyranitar": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Houndoom": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Absol": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Alakazam": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Garchomp": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Lucario": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Abomasnow": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Slowbro": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Gallade": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Altaria": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Metagross": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },

    "Mega Diancie": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Hoopa": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Latias": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Latios": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Rayquaza": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Lopunny": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Salamence": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Sharpedo": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Camerupt": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Glalie": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Audino": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Banette": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Sceptile": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Blaziken": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Swampert": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Mewtwo X": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Mewtwo Y": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Medicham": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Manectric": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Beedrill": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Pidgeot": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Victreebel": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
    "Mega Froslass": {
        "level": 50,
        "evs": {"hp":4,"at":252,"df":0,"sa":0,"sd":0,"sp":252},
        "nature": "Jolly",
        "moves": ["Dragon Claw","Earthquake","Roost","Protect"],
    },
};